module.exports = {
  __init__: [
    'adaptiveLabelPositioningBehavior',
    'appendBehavior',
    'copyPasteBehavior',
    'createBoundaryEventBehavior',
    'createDataObjectBehavior',
    'createParticipantBehavior',
    'dataInputAssociationBehavior',
    'deleteLaneBehavior',
    'dropOnFlowBehavior',
    'importDockingFix',
    'labelBehavior',
    'modelingFeedback',
    'removeElementBehavior',
    'removeParticipantBehavior',
    'replaceConnectionBehavior',
    'replaceElementBehaviour',
    'resizeLaneBehavior',
    'toggleElementCollapseBehaviour',
    'unclaimIdBehavior',
    'unsetDefaultFlowBehavior',
    'updateFlowNodeRefsBehavior'
  ],
  adaptiveLabelPositioningBehavior: [ 'type', require('./AdaptiveLabelPositioningBehavior') ],
  appendBehavior: [ 'type', require('./AppendBehavior') ],
  copyPasteBehavior: [ 'type', require('./CopyPasteBehavior') ],
  createBoundaryEventBehavior: [ 'type', require('./CreateBoundaryEventBehavior') ],
  createDataObjectBehavior: [ 'type', require('./CreateDataObjectBehavior') ],
  createParticipantBehavior: [ 'type', require('./CreateParticipantBehavior') ],
  dataInputAssociationBehavior: [ 'type', require('./DataInputAssociationBehavior') ],
  deleteLaneBehavior: [ 'type', require('./DeleteLaneBehavior') ],
  dropOnFlowBehavior: [ 'type', require('./DropOnFlowBehavior') ],
  importDockingFix: [ 'type', require('./ImportDockingFix') ],
  labelBehavior: [ 'type', require('./LabelBehavior') ],
  modelingFeedback: [ 'type', require('./ModelingFeedback') ],
  replaceConnectionBehavior: [ 'type', require('./ReplaceConnectionBehavior') ],
  removeParticipantBehavior: [ 'type', require('./RemoveParticipantBehavior') ],
  replaceElementBehaviour: [ 'type', require('./ReplaceElementBehaviour') ],
  resizeLaneBehavior: [ 'type', require('./ResizeLaneBehavior') ],
  removeElementBehavior: [ 'type', require('./RemoveElementBehavior') ],
  toggleElementCollapseBehaviour : [ 'type', require('./ToggleElementCollapseBehaviour') ],
  unclaimIdBehavior: [ 'type', require('./UnclaimIdBehavior') ],
  updateFlowNodeRefsBehavior: [ 'type', require('./UpdateFlowNodeRefsBehavior') ],
  unsetDefaultFlowBehavior: [ 'type', require('./UnsetDefaultFlowBehavior') ]
};
