#! /bin/sh

# updates the bpmn-js-seed project with the latest bundle

PWD="$(pwd)"
WORKDIR="$(pwd)/tmp"
SEED_DIR="$WORKDIR/bpmn-js-seed"

# create work dir
mkdir -p "$WORKDIR"

git clone --depth=1 https://github.com/bpmn-io/bpmn-js-seed.git "$SEED_DIR"

npm install -g bower

cd "$SEED_DIR"

bower install "bpmn-js@$TRAVIS_TAG" -f

git config user.email "$BPMN_IO_EMAIL"
git config user.name "$BPMN_IO_USERNAME"
git config push.default simple

git add -A
git commit -m "chore(seed): update to bpmn-js $TRAVIS_TAG"
git tag "$TRAVIS_TAG"
git push -q "https://$GITHUB_AUTH@github.com/bpmn-io/bpmn-js-seed.git" &2>/dev/null
git push --tags -q "https://$GITHUB_AUTH@github.com/bpmn-io/bpmn-js-seed.git" &2>/dev/null

cd "$PWD"