name: PR
on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

permissions:
  contents: read
  pull-requests: read

jobs:
  Validate:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR quality
        uses: bpmn-io/actions/pull-request-quality@dadd26245e7ccf2399bafb558cf2ca29c8b44f9e
